name: deeplink_rpc
description: A RPC-via-deeplink command receiver.
version: 1.0.0-dev.1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  url_launcher: ^6.1.9

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.5.4

  lints: ^2.0.0
  test: ^1.16.0
  freezed: ^2.3.2

