# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner",
    export_options: {
      provisioningProfiles: { 
        "tech.archethic.wallet" => "Archethic Wallet Mac",
      }
    },
    installer_cert_name: "3rd Party Mac Developer Installer: Archethic Technologies SARL (2QGGN9QQKR)")
    upload_to_app_store
  end

  desc "Push a new release build to TestFlight"
  lane :beta do
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner",  
    export_options: {
      provisioningProfiles: { 
        "tech.archethic.wallet" => "Archethic Wallet Mac",
      }
    },
    installer_cert_name: "3rd Party Mac Developer Installer: Archethic Technologies SARL (2QGGN9QQKR)")
    upload_to_testflight
    end
end
