# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Push a new release build to the App Store"
  lane :release do
    version_code = getVersionCode(getVersionInfo())
    version_name = getVersionName(getVersionInfo())
    flutter_build(version_name,version_code, "macos")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner",
    export_options: {
      provisioningProfiles: { 
        "tech.archethic.wallet" => "Archethic Wallet Mac",
      }
    },
    installer_cert_name: "3rd Party Mac Developer Installer: Archethic Technologies SARL (2QGGN9QQKR)")
    upload_to_app_store
  end

  desc "Push a new release build to TestFlight"
  lane :beta do
    version_code = getVersionCode(getVersionInfo())
    version_name = getVersionName(getVersionInfo())
    flutter_build(version_name,version_code, "macos")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner",  
    export_options: {
      provisioningProfiles: { 
        "tech.archethic.wallet" => "Archethic Wallet Mac",
      }
    },
    installer_cert_name: "3rd Party Mac Developer Installer: Archethic Technologies SARL (2QGGN9QQKR)")
    upload_to_testflight
    end

  desc "Build a new release"
  lane :build do
    version_code = getVersionCode(getVersionInfo())
    version_name = getVersionName(getVersionInfo())
    flutter_build(version_name,version_code, "macos")
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner",  
    export_options: {
      provisioningProfiles: { 
        "tech.archethic.wallet" => "Archethic Wallet Mac",
      }
    },
    installer_cert_name: "3rd Party Mac Developer Installer: Archethic Technologies SARL (2QGGN9QQKR)")
      
    end
end

def getVersionInfo()
  version_info = flutter_version(
    pubspec_location: '../pubspec.yaml'
  )
end

def getVersionCode(version_info)
  return version_info['version_code']
end

def getVersionName(version_info)
  return version_info['version_name']
end


def flutter_build(versionName,number,format)
  Dir.chdir '.' do
    sh('flutter', 'packages', 'get')
    sh('flutter', 'clean')
    sh(
      "flutter build #{format} --obfuscate --split-debug-info=build/sym/#{format} --build-name=#{
        versionName
      } --build-number=#{number.to_s} "
    )
  end
end