// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkJy0b-2ezBoNe8YYSdmHy71t_s2B8g00',
    appId: '1:329689363769:web:8836677f01a017c40fe4e8',
    messagingSenderId: '329689363769',
    projectId: 'ae-wallet',
    authDomain: 'ae-wallet.firebaseapp.com',
    storageBucket: 'ae-wallet.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq41eMXuRmyMwqAxub0b3aWEFT36jDds4',
    appId: '1:329689363769:android:404e2e22d694f07d0fe4e8',
    messagingSenderId: '329689363769',
    projectId: 'ae-wallet',
    storageBucket: 'ae-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz3x3eLLAzs3DXAQWXN5S9JkMqDTNKahs',
    appId: '1:329689363769:ios:a0df2fae4b37b34b0fe4e8',
    messagingSenderId: '329689363769',
    projectId: 'ae-wallet',
    storageBucket: 'ae-wallet.appspot.com',
    iosClientId: '329689363769-rstsnvo072vu861fhn0v5auel16ji7v4.apps.googleusercontent.com',
    iosBundleId: 'tech.archethic.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz3x3eLLAzs3DXAQWXN5S9JkMqDTNKahs',
    appId: '1:329689363769:ios:a0df2fae4b37b34b0fe4e8',
    messagingSenderId: '329689363769',
    projectId: 'ae-wallet',
    storageBucket: 'ae-wallet.appspot.com',
    iosClientId: '329689363769-rstsnvo072vu861fhn0v5auel16ji7v4.apps.googleusercontent.com',
    iosBundleId: 'tech.archethic.wallet',
  );
}
