# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  desc "Publish to iOS App Store"
  lane :release do
    version_code = getVersionCode(getVersionInfo())
    version_name = getVersionName(getVersionInfo())
    flutter_build(version_name,version_code, "ios")
    build_ios_app(workspace: "ios/Runner.xcworkspace", scheme: "Runner")
    upload_to_app_store
  end
  
  desc "Publish to iOS TestFlight"
  lane :beta do
    version_code = getVersionCode(getVersionInfo())
    version_name = getVersionName(getVersionInfo())
    flutter_build(version_name,version_code, "ios")
    build_ios_app(workspace: "ios/Runner.xcworkspace", scheme: "Runner")
    upload_to_testflight
  end
end

platform :mac do
  desc "Publish to MacOS App Store"
  lane :release do
    version_code = getVersionCode(getVersionInfo())
    version_name = getVersionName(getVersionInfo())
    flutter_build(version_name,version_code, "macos")
    build_mac_app(workspace: "macos/Runner.xcworkspace", scheme: "Runner",
    export_options: {
      provisioningProfiles: { 
        "tech.archethic.wallet" => "Archethic Wallet Mac",
      }
    },
    installer_cert_name: "3rd Party Mac Developer Installer: Archethic Technologies SARL (2QGGN9QQKR)")
    upload_to_app_store(pkg: "archethic_wallet.pkg")
  end
  
  desc "Publish to MacOS TestFlight"
  lane :beta do
    version_code = getVersionCode(getVersionInfo())
    version_name = getVersionName(getVersionInfo())
    flutter_build(version_name,version_code, "macos")
    build_mac_app(workspace: "macos/Runner.xcworkspace", scheme: "Runner",  
    export_options: {
      provisioningProfiles: { 
        "tech.archethic.wallet" => "Archethic Wallet Mac",
      }
    },
    installer_cert_name: "3rd Party Mac Developer Installer: Archethic Technologies SARL (2QGGN9QQKR)")
    upload_to_testflight
  end
end

platform :android do
  desc "Publish to GooglePlay"
  lane :release do 
    version_code = getVersionCode(getVersionInfo())
    version_name = getVersionName(getVersionInfo())
    flutter_build(version_name,version_code, "appbundle")
    
    upload_to_play_store(
      track: 'production',
      version_code: version_code,
      aab: 'build/app/outputs/bundle/release/app-release.aab',
    )
  end
    
  desc "Publish to GooglePlay Beta"
  lane :beta do 
    desc "Deploy to beta canal"
    version_code = getVersionCode(getVersionInfo())
    version_name = getVersionName(getVersionInfo())
    flutter_build(version_name,version_code, "appbundle")

    upload_to_play_store(
      track: 'beta',
      version_code: version_code,
      aab: 'build/app/outputs/bundle/release/app-release.aab',
    )
  end
end

def getVersionInfo()
  version_info = flutter_version(
    pubspec_location: 'pubspec.yaml'
  )
end

def getVersionCode(version_info)
  return version_info['version_code']
end

def getVersionName(version_info)
  return version_info['version_name']
end


def flutter_build(versionName,number,format)
  Dir.chdir '.' do
    sh('flutter', 'packages', 'get')
    sh('flutter', 'clean')
    sh(
      "flutter build #{format} --obfuscate --split-debug-info=build/sym/#{format} --build-name=#{
        versionName
      } --build-number=#{number.to_s} --dart-define=AIRDROP_SECRET=\"#{ENV['airdropSecret']}\" --dart-define=HCAPTCHA_SECRET_SITEKEY=\"#{ENV['hcaptchaSecretSiteKey']}\""
    )
  end
end
