# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
import './FastlaneUtils'

platform :mac do
  desc "Push a new release build to the App Store"
  lane :release do
    apple_build("macos")
    upload_to_app_store(
      build_number: version_code
    )
  end

  desc "Push a new release build to TestFlight"
  lane :beta do
    apple_build("macos")
    upload_to_testflight(
      build_number: version_code
    )
  end
end

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    apple_build("ios")
    upload_to_app_store(
      build_number: version_code
    )
  end

  desc "Push a new release build to TestFlight"
  lane :beta do
    apple_build("ios")
    upload_to_testflight(
      build_number: version_code
    )
  end
end

platform :android do
  desc "Publish to GooglePlay"
  lane :release do
    flutter_build("appbundle")

    upload_to_play_store(
      track: 'production',
      version_code: version_code,
      aab: './build/app/outputs/bundle/release/app-release.aab',
    )
  end

  desc "Publish to GooglePlay Beta"
  lane :beta do
    desc "Deploy to beta canal"
    flutter_build("appbundle")

    upload_to_play_store(
      track: 'beta',
      version_code: version_code,
      aab: './build/app/outputs/bundle/release/app-release.aab',
    )
  end


  desc "Publish to GooglePlay Alpha"
  lane :alpha do
    desc "Deploy to alpha canal"
    flutter_build("appbundle")

    upload_to_play_store(
      track: 'alpha',
      version_code: version_code,
      aab: './build/app/outputs/bundle/release/app-release.aab',
    )
  end
end
