name: Build and Package Linux AppImage

on:
  push:
    branches:
      - dev
      - packaging-github-actions
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version

      - name: Setup Dependencies
        run: |
          flutter doctor
          sudo apt-get update -y
          sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libsecret-1-dev libjsoncpp-dev fuse libgtk-3-0 python3-pip libgtkmm-3.0-1v5 libnotify4 gstreamer1.0-tools

      - name: Build Flutter Application
        run: flutter build linux --release

      - name: Install appimage-builder
        run: |
          sudo pip3 install appimage-builder

      - name: Generate AppImage
        run: |
          appimage-builder --recipe AppImageBuilder.yml --skip-test

      - name: Check files
        run: |
          ls -R

      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v1
        with:
          name: archethic-wallet-appimage
          path: archethic-wallet-latest-x86_64.AppImage
