name: Build and Package Windows app

on:
  push:
    branches:
      - dev
      - packaging-github-actions
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version

      - name: Setup dependencies
        run: |
          flutter doctor
          choco install cmake ninja python3
          choco install -y visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

      - name: Build Flutter Application
        run: flutter build windows --release

      - name: Get Version from pubspec.yaml
        id: get_version
        run: echo "version=$(awk '/^version:/{print $2}' pubspec.yaml)" >> $GITHUB_ENV

      - name: Archive Artifact
        run: |
          mkdir artifacts
          mv build/windows/runner/Release/ archethic-wallet
          Compress-Archive -Path archethic-wallet -DestinationPath "artifacts/archethic-wallet-${{ env.version }}.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: archethic-wallet-windows-${{ env.version }}
          path: artifacts/archethic-wallet-${{ env.version }}.zip
